development:
  adapter: mysql2
  database: bisyoujo_zukan_night_development
  host: localhost
  username: root
  password:
  pool: 5
  timeout: 5000
  encoding: utf8
  port: 3306
  collation: utf8_general_ci


production:
  adapter: mysql2
  database: kirekawa_night_production
  host: localhost
  username: root
  password: "kirekawa2016"
  pool: 5
  timeout: 5000
  encoding: utf8
  port: 3306
  collation: utf8_general_ci
